//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Animation/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""CharacterControls"",
            ""id"": ""fe68c842-8986-4290-808f-da74497b6cf1"",
            ""actions"": [
                {
                    ""name"": ""PlayerAMove"",
                    ""type"": ""Value"",
                    ""id"": ""4dda39be-f01c-4202-97b9-a4dbd53bac23"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlayerARun"",
                    ""type"": ""Button"",
                    ""id"": ""d376715b-bf62-43fa-889a-00b349878567"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayerAJump"",
                    ""type"": ""Button"",
                    ""id"": ""b31e9c05-a658-4101-992c-015e1873376d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayerACast1"",
                    ""type"": ""Button"",
                    ""id"": ""78151fce-c9e8-4d59-a427-e740e6861f82"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayerACast2"",
                    ""type"": ""Button"",
                    ""id"": ""ee91f23b-54f8-45fd-9079-e57090be4fb4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayerACast3"",
                    ""type"": ""Button"",
                    ""id"": ""df8c50ed-7540-46f9-acd7-7ccfc4733211"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""e7d3032d-0207-480e-a057-35b3bc37bb2f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayerBMove"",
                    ""type"": ""Value"",
                    ""id"": ""4474efde-84ee-4541-bb3e-7c9bb739ed2f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlayerBRun"",
                    ""type"": ""Button"",
                    ""id"": ""bc567b6c-52dd-413d-b469-79be94a82929"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayerBJump"",
                    ""type"": ""Button"",
                    ""id"": ""826773cb-88a7-431d-92c4-b0f3095c8bc7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayerBCast1"",
                    ""type"": ""Button"",
                    ""id"": ""0f589329-0b99-4ab8-a023-0991acdf95ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayerBCast2"",
                    ""type"": ""Button"",
                    ""id"": ""b9e3fa00-fb5c-4ac1-809b-06f8e9d5fb74"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayerBCast3"",
                    ""type"": ""Button"",
                    ""id"": ""e855e1ee-e08f-4d28-8cad-7d7c2f274572"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""07924e31-f483-433a-802b-093afe09e608"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerAMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9ae4fde6-b2b5-4d55-8632-eb92f269b93f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerAMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7d2ad273-2089-4f95-9b00-81c3e6885bcd"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerAMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""972bb32e-a70d-41df-9380-67228e708e55"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerARun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dce548f0-c383-40e9-a3ea-3bddf7fc99b8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerAJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c7c0b3b-f067-48d5-b352-542ce6758693"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerACast1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b090bc6-215b-4392-a39a-75f873e5c3ba"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerACast1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b33f5380-7b28-4f39-97cc-c30fa4e8be16"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerACast2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""685e94d4-52d3-401d-95ba-6dc2ab6d1127"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerACast2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aad7ead3-f316-4fda-98c9-8f1d730d502d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerACast3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66542fdf-b1d5-4220-80ec-f5d69d977506"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerACast3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b056fe67-4d2d-4e1d-9f2e-847c6f50626b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2ecbfe2d-348a-45cd-a78e-93451d04e570"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerBMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9af2bd66-e09b-4f98-9447-4ecc6245bdb7"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerBMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""49d54084-8529-476f-90b6-2f3e913af749"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerBMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f93ed3b1-c6ff-4df6-9a0e-e8501ec5d983"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerBRun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88883c30-a027-4d35-b749-1b97d984519a"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerBJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41913a57-e4b5-40a5-b970-df4989597690"",
                    ""path"": ""<Keyboard>/slash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerBCast1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8eaa2069-6745-4ed2-b410-bd970e0ae897"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerBCast2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae02ed33-8148-4d4c-94c6-96d87f889e81"",
                    ""path"": ""<Keyboard>/quote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerBCast3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CharacterControls
        m_CharacterControls = asset.FindActionMap("CharacterControls", throwIfNotFound: true);
        m_CharacterControls_PlayerAMove = m_CharacterControls.FindAction("PlayerAMove", throwIfNotFound: true);
        m_CharacterControls_PlayerARun = m_CharacterControls.FindAction("PlayerARun", throwIfNotFound: true);
        m_CharacterControls_PlayerAJump = m_CharacterControls.FindAction("PlayerAJump", throwIfNotFound: true);
        m_CharacterControls_PlayerACast1 = m_CharacterControls.FindAction("PlayerACast1", throwIfNotFound: true);
        m_CharacterControls_PlayerACast2 = m_CharacterControls.FindAction("PlayerACast2", throwIfNotFound: true);
        m_CharacterControls_PlayerACast3 = m_CharacterControls.FindAction("PlayerACast3", throwIfNotFound: true);
        m_CharacterControls_LeftClick = m_CharacterControls.FindAction("LeftClick", throwIfNotFound: true);
        m_CharacterControls_PlayerBMove = m_CharacterControls.FindAction("PlayerBMove", throwIfNotFound: true);
        m_CharacterControls_PlayerBRun = m_CharacterControls.FindAction("PlayerBRun", throwIfNotFound: true);
        m_CharacterControls_PlayerBJump = m_CharacterControls.FindAction("PlayerBJump", throwIfNotFound: true);
        m_CharacterControls_PlayerBCast1 = m_CharacterControls.FindAction("PlayerBCast1", throwIfNotFound: true);
        m_CharacterControls_PlayerBCast2 = m_CharacterControls.FindAction("PlayerBCast2", throwIfNotFound: true);
        m_CharacterControls_PlayerBCast3 = m_CharacterControls.FindAction("PlayerBCast3", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CharacterControls
    private readonly InputActionMap m_CharacterControls;
    private ICharacterControlsActions m_CharacterControlsActionsCallbackInterface;
    private readonly InputAction m_CharacterControls_PlayerAMove;
    private readonly InputAction m_CharacterControls_PlayerARun;
    private readonly InputAction m_CharacterControls_PlayerAJump;
    private readonly InputAction m_CharacterControls_PlayerACast1;
    private readonly InputAction m_CharacterControls_PlayerACast2;
    private readonly InputAction m_CharacterControls_PlayerACast3;
    private readonly InputAction m_CharacterControls_LeftClick;
    private readonly InputAction m_CharacterControls_PlayerBMove;
    private readonly InputAction m_CharacterControls_PlayerBRun;
    private readonly InputAction m_CharacterControls_PlayerBJump;
    private readonly InputAction m_CharacterControls_PlayerBCast1;
    private readonly InputAction m_CharacterControls_PlayerBCast2;
    private readonly InputAction m_CharacterControls_PlayerBCast3;
    public struct CharacterControlsActions
    {
        private @PlayerInput m_Wrapper;
        public CharacterControlsActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @PlayerAMove => m_Wrapper.m_CharacterControls_PlayerAMove;
        public InputAction @PlayerARun => m_Wrapper.m_CharacterControls_PlayerARun;
        public InputAction @PlayerAJump => m_Wrapper.m_CharacterControls_PlayerAJump;
        public InputAction @PlayerACast1 => m_Wrapper.m_CharacterControls_PlayerACast1;
        public InputAction @PlayerACast2 => m_Wrapper.m_CharacterControls_PlayerACast2;
        public InputAction @PlayerACast3 => m_Wrapper.m_CharacterControls_PlayerACast3;
        public InputAction @LeftClick => m_Wrapper.m_CharacterControls_LeftClick;
        public InputAction @PlayerBMove => m_Wrapper.m_CharacterControls_PlayerBMove;
        public InputAction @PlayerBRun => m_Wrapper.m_CharacterControls_PlayerBRun;
        public InputAction @PlayerBJump => m_Wrapper.m_CharacterControls_PlayerBJump;
        public InputAction @PlayerBCast1 => m_Wrapper.m_CharacterControls_PlayerBCast1;
        public InputAction @PlayerBCast2 => m_Wrapper.m_CharacterControls_PlayerBCast2;
        public InputAction @PlayerBCast3 => m_Wrapper.m_CharacterControls_PlayerBCast3;
        public InputActionMap Get() { return m_Wrapper.m_CharacterControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterControlsActions set) { return set.Get(); }
        public void SetCallbacks(ICharacterControlsActions instance)
        {
            if (m_Wrapper.m_CharacterControlsActionsCallbackInterface != null)
            {
                @PlayerAMove.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerAMove;
                @PlayerAMove.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerAMove;
                @PlayerAMove.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerAMove;
                @PlayerARun.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerARun;
                @PlayerARun.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerARun;
                @PlayerARun.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerARun;
                @PlayerAJump.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerAJump;
                @PlayerAJump.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerAJump;
                @PlayerAJump.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerAJump;
                @PlayerACast1.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerACast1;
                @PlayerACast1.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerACast1;
                @PlayerACast1.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerACast1;
                @PlayerACast2.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerACast2;
                @PlayerACast2.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerACast2;
                @PlayerACast2.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerACast2;
                @PlayerACast3.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerACast3;
                @PlayerACast3.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerACast3;
                @PlayerACast3.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerACast3;
                @LeftClick.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnLeftClick;
                @LeftClick.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnLeftClick;
                @LeftClick.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnLeftClick;
                @PlayerBMove.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerBMove;
                @PlayerBMove.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerBMove;
                @PlayerBMove.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerBMove;
                @PlayerBRun.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerBRun;
                @PlayerBRun.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerBRun;
                @PlayerBRun.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerBRun;
                @PlayerBJump.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerBJump;
                @PlayerBJump.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerBJump;
                @PlayerBJump.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerBJump;
                @PlayerBCast1.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerBCast1;
                @PlayerBCast1.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerBCast1;
                @PlayerBCast1.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerBCast1;
                @PlayerBCast2.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerBCast2;
                @PlayerBCast2.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerBCast2;
                @PlayerBCast2.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerBCast2;
                @PlayerBCast3.started -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerBCast3;
                @PlayerBCast3.performed -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerBCast3;
                @PlayerBCast3.canceled -= m_Wrapper.m_CharacterControlsActionsCallbackInterface.OnPlayerBCast3;
            }
            m_Wrapper.m_CharacterControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PlayerAMove.started += instance.OnPlayerAMove;
                @PlayerAMove.performed += instance.OnPlayerAMove;
                @PlayerAMove.canceled += instance.OnPlayerAMove;
                @PlayerARun.started += instance.OnPlayerARun;
                @PlayerARun.performed += instance.OnPlayerARun;
                @PlayerARun.canceled += instance.OnPlayerARun;
                @PlayerAJump.started += instance.OnPlayerAJump;
                @PlayerAJump.performed += instance.OnPlayerAJump;
                @PlayerAJump.canceled += instance.OnPlayerAJump;
                @PlayerACast1.started += instance.OnPlayerACast1;
                @PlayerACast1.performed += instance.OnPlayerACast1;
                @PlayerACast1.canceled += instance.OnPlayerACast1;
                @PlayerACast2.started += instance.OnPlayerACast2;
                @PlayerACast2.performed += instance.OnPlayerACast2;
                @PlayerACast2.canceled += instance.OnPlayerACast2;
                @PlayerACast3.started += instance.OnPlayerACast3;
                @PlayerACast3.performed += instance.OnPlayerACast3;
                @PlayerACast3.canceled += instance.OnPlayerACast3;
                @LeftClick.started += instance.OnLeftClick;
                @LeftClick.performed += instance.OnLeftClick;
                @LeftClick.canceled += instance.OnLeftClick;
                @PlayerBMove.started += instance.OnPlayerBMove;
                @PlayerBMove.performed += instance.OnPlayerBMove;
                @PlayerBMove.canceled += instance.OnPlayerBMove;
                @PlayerBRun.started += instance.OnPlayerBRun;
                @PlayerBRun.performed += instance.OnPlayerBRun;
                @PlayerBRun.canceled += instance.OnPlayerBRun;
                @PlayerBJump.started += instance.OnPlayerBJump;
                @PlayerBJump.performed += instance.OnPlayerBJump;
                @PlayerBJump.canceled += instance.OnPlayerBJump;
                @PlayerBCast1.started += instance.OnPlayerBCast1;
                @PlayerBCast1.performed += instance.OnPlayerBCast1;
                @PlayerBCast1.canceled += instance.OnPlayerBCast1;
                @PlayerBCast2.started += instance.OnPlayerBCast2;
                @PlayerBCast2.performed += instance.OnPlayerBCast2;
                @PlayerBCast2.canceled += instance.OnPlayerBCast2;
                @PlayerBCast3.started += instance.OnPlayerBCast3;
                @PlayerBCast3.performed += instance.OnPlayerBCast3;
                @PlayerBCast3.canceled += instance.OnPlayerBCast3;
            }
        }
    }
    public CharacterControlsActions @CharacterControls => new CharacterControlsActions(this);
    public interface ICharacterControlsActions
    {
        void OnPlayerAMove(InputAction.CallbackContext context);
        void OnPlayerARun(InputAction.CallbackContext context);
        void OnPlayerAJump(InputAction.CallbackContext context);
        void OnPlayerACast1(InputAction.CallbackContext context);
        void OnPlayerACast2(InputAction.CallbackContext context);
        void OnPlayerACast3(InputAction.CallbackContext context);
        void OnLeftClick(InputAction.CallbackContext context);
        void OnPlayerBMove(InputAction.CallbackContext context);
        void OnPlayerBRun(InputAction.CallbackContext context);
        void OnPlayerBJump(InputAction.CallbackContext context);
        void OnPlayerBCast1(InputAction.CallbackContext context);
        void OnPlayerBCast2(InputAction.CallbackContext context);
        void OnPlayerBCast3(InputAction.CallbackContext context);
    }
}
